import type { Product, Category } from "@shared/schema";

export const mockProducts: Product[] = [
  {
    id: 1,
    title: "Vintage Levi's Denim Jacket",
    description: "Classic 90s style denim jacket in excellent condition. Size M. Perfect for layering.",
    price: "45.00",
    originalPrice: "120.00",
    condition: "excellent",
    status: "available",
    categoryId: 2,
    sellerId: "seller1",
    brand: "Levi's",
    size: "M",
    color: "Blue",
    material: "Denim",
    images: ["https://images.unsplash.com/photo-1551698618-1dfe5d97d256?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300"],
    location: "Adelaide, SA",
    shippingCost: "15.00",
    isVerified: false,
    views: 127,
    likes: 23,
    createdAt: new Date("2025-01-20"),
    updatedAt: new Date("2025-01-20"),
  },
  {
    id: 2,
    title: "Mid-Century Modern Armchair",
    description: "Beautiful mustard yellow armchair from the 1960s. Some minor wear but still comfortable.",
    price: "285.00",
    originalPrice: "650.00",
    condition: "good",
    status: "available",
    categoryId: 5,
    sellerId: "seller2",
    brand: "Unknown",
    size: null,
    color: "Mustard Yellow",
    material: "Fabric",
    images: ["https://images.unsplash.com/photo-1586023492125-27b2c045efd7?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300"],
    location: "Melbourne, VIC",
    shippingCost: "45.00",
    isVerified: false,
    views: 89,
    likes: 31,
    createdAt: new Date("2025-01-19"),
    updatedAt: new Date("2025-01-19"),
  },
  {
    id: 3,
    title: "iPhone 12 - 128GB",
    description: "Pacific Blue iPhone 12 in like-new condition. Unlocked, 95% battery health. Includes original box.",
    price: "545.00",
    originalPrice: "999.00",
    condition: "excellent",
    status: "available",
    categoryId: 4,
    sellerId: "seller3",
    brand: "Apple",
    size: "128GB",
    color: "Pacific Blue",
    material: "Glass/Aluminum",
    images: ["https://images.unsplash.com/photo-1592750475338-74b7b21085ab?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300"],
    location: "Sydney, NSW",
    shippingCost: "12.00",
    isVerified: true,
    views: 234,
    likes: 67,
    createdAt: new Date("2025-01-18"),
    updatedAt: new Date("2025-01-18"),
  },
  {
    id: 4,
    title: "Handmade Ceramic Vase Set",
    description: "Set of 3 beautiful handmade ceramic vases in earth tones. Perfect for modern home decor.",
    price: "75.00",
    originalPrice: "150.00",
    condition: "excellent",
    status: "available",
    categoryId: 3,
    sellerId: "seller4",
    brand: "Artisan Made",
    size: "Various",
    color: "Earth Tones",
    material: "Ceramic",
    images: ["https://images.unsplash.com/photo-1578662996442-48f60103fc96?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300"],
    location: "Brisbane, QLD",
    shippingCost: "18.00",
    isVerified: false,
    views: 156,
    likes: 42,
    createdAt: new Date("2025-01-17"),
    updatedAt: new Date("2025-01-17"),
  },
  {
    id: 5,
    title: "Designer Dark Wash Jeans",
    description: "Premium denim jeans in dark wash, size 32W. Barely worn, still has tags.",
    price: "95.00",
    originalPrice: "250.00",
    condition: "excellent",
    status: "available",
    categoryId: 2,
    sellerId: "seller1",
    brand: "Designer Brand",
    size: "32W",
    color: "Dark Blue",
    material: "Denim",
    images: ["https://images.unsplash.com/photo-1542272604-787c3835535d?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300"],
    location: "Perth, WA",
    shippingCost: "12.00",
    isVerified: false,
    views: 78,
    likes: 19,
    createdAt: new Date("2025-01-16"),
    updatedAt: new Date("2025-01-16"),
  },
  {
    id: 6,
    title: "Teak Coffee Table",
    description: "Mid-century modern teak coffee table from the 1960s. Solid wood construction with beautiful grain.",
    price: "425.00",
    originalPrice: "800.00",
    condition: "good",
    status: "available",
    categoryId: 5,
    sellerId: "seller2",
    brand: "Danish Modern",
    size: "120cm x 60cm",
    color: "Natural Teak",
    material: "Teak Wood",
    images: ["https://images.unsplash.com/photo-1555041469-a586c61ea9bc?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300"],
    location: "Darwin, NT",
    shippingCost: "65.00",
    isVerified: false,
    views: 203,
    likes: 58,
    createdAt: new Date("2025-01-15"),
    updatedAt: new Date("2025-01-15"),
  },
  {
    id: 7,
    title: "MacBook Pro 13\" M1",
    description: "Apple MacBook Pro with M1 chip, 256GB SSD, 8GB RAM in Space Gray. Excellent performance.",
    price: "1299.00",
    originalPrice: "1999.00",
    condition: "excellent",
    status: "available",
    categoryId: 4,
    sellerId: "seller3",
    brand: "Apple",
    size: "13 inch",
    color: "Space Gray",
    material: "Aluminum",
    images: ["https://images.unsplash.com/photo-1496181133206-80ce9b88a853?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300"],
    location: "Canberra, ACT",
    shippingCost: "25.00",
    isVerified: true,
    views: 456,
    likes: 123,
    createdAt: new Date("2025-01-14"),
    updatedAt: new Date("2025-01-14"),
  },
  {
    id: 8,
    title: "70s Vintage Floral Dress",
    description: "Authentic 1970s vintage floral dress in excellent condition. Size 10, perfect boho style.",
    price: "89.00",
    originalPrice: "180.00",
    condition: "excellent",
    status: "available",
    categoryId: 2,
    sellerId: "seller4",
    brand: "Vintage",
    size: "10",
    color: "Floral Print",
    material: "Cotton Blend",
    images: ["https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?ixlib=rb-4.0.3&auto=format&fit=crop&w=400&h=300"],
    location: "Hobart, TAS",
    shippingCost: "14.00",
    isVerified: false,
    views: 167,
    likes: 34,
    createdAt: new Date("2025-01-13"),
    updatedAt: new Date("2025-01-13"),
  },
];

export const mockCategories: Category[] = [
  { id: 1, name: "New Arrivals", slug: "new-arrivals", description: "Recently listed items", parentId: null, isActive: true, createdAt: new Date() },
  { id: 2, name: "Clothing", slug: "clothing", description: "Men, Women, Kids clothing", parentId: null, isActive: true, createdAt: new Date() },
  { id: 3, name: "Homewares", slug: "homewares", description: "Home decor and kitchenware", parentId: null, isActive: true, createdAt: new Date() },
  { id: 4, name: "Electronics", slug: "electronics", description: "Gadgets and technology", parentId: null, isActive: true, createdAt: new Date() },
  { id: 5, name: "Furniture", slug: "furniture", description: "Home and office furniture", parentId: null, isActive: true, createdAt: new Date() },
  { id: 6, name: "Sports", slug: "sports", description: "Sports equipment and gear", parentId: null, isActive: true, createdAt: new Date() },
  { id: 7, name: "Entertainment", slug: "entertainment", description: "Books, games, media", parentId: null, isActive: true, createdAt: new Date() },
  { id: 8, name: "Bric-a-brac", slug: "bric-a-brac", description: "Collectibles and misc items", parentId: null, isActive: true, createdAt: new Date() },
];
