ALTER TABLE "products" ADD COLUMN "clothing_size" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "clothing_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "clothing_gender" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "model" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "storage_capacity" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "screen_size" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "battery_life" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "connectivity" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "make" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "vehicle_model" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "year" integer;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "kilometers" integer;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "fuel_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "transmission" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "body_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "engine_size" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "drivetrain" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "registration_state" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "room_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "furniture_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "dimensions" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "assembly_required" boolean;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "sport_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "activity_level" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "equipment_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "author" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "isbn" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "publisher" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "publication_year" integer;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "language" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "format" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "genre" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "age_range" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "safety_standard" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "educational_value" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "skin_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "hair_type" varchar;--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "ingredients" text[] DEFAULT '{}';--> statement-breakpoint
ALTER TABLE "products" ADD COLUMN "expiry_date" timestamp;